//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pacesetter
{
    using System;
    using System.Collections.Generic;
    
    public partial class goal_table
    {
        public int Goal_id { get; set; }
        public string GoalName { get; set; }
        public string GoalDescription { get; set; }
        public Nullable<int> GoalCategoryId { get; set; }
        public string GoalCategoryName { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual goal_category goal_category { get; set; }
    }
}
